feat: wordpress setup added, not working yet

diff --git a/srcs/requirements/wordpress/Dockerfile b/srcs/requirements/wordpress/Dockerfile
--- a/srcs/requirements/wordpress/Dockerfile
+++ b/srcs/requirements/wordpress/Dockerfile
@@ -22,16 +22,27 @@ RUN apk add --no-cache \
 RUN		mkdir -p /var/www/wordpress
 WORKDIR	/var/www/wordpress
 
-# Download WP-CLI
-RUN curl -o wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
-	&& chmod +x wp-cli.phar \
-	&& mv wp-cli.phar /usr/local/bin/wp
+# Download and install WP-CLI
+RUN		curl -o wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
+		&& chmod +x wp-cli.phar \
+		&& mv wp-cli.phar /usr/local/bin/wp
+
+# Create user to run WP and PHP
+# -S: create system group
+# || true: if group already exists, build doesn't fail
+# -D: create a default user (no password, no home directory unless specified)
+# -S: mark as system user (no login, no home directory)
+# -G www-data: add user to the group www-data
+# www-data: name of the user
+RUN		addgroup -S www-data || true \
+		&& adduser -D -S -G www-data www-data
 
 # Set permissions for wordpress
-# RUN	chown -R www-data:www-data /var/www/html
+RUN		chown -R www-data:www-data /var/www/wordpress
 
-# Download wordpress
-RUN		wp core download --allow-root
+# Copy wordpress initialization config to
+COPY tools/conf.sh /conf.sh
+RUN chmod +x /conf.sh
 
 # Copy PHP-FPM pool config
 COPY	/conf/www.conf /etc/php7/php-fpm.d/www.conf
@@ -39,4 +50,9 @@ COPY	/conf/www.conf /etc/php7/php-fpm.d/www.conf
 # Expose php-fpm port
 EXPOSE	9000
 
+# Set configuration script as entrypoint for docker
+ENTRYPOINT ["/conf.sh"]
+
+# Launch FastCGI Process Manager.
+# -F: keep as PID 1 in foreground
 CMD ["php-fpm7", "-F"]
